server.port=8080
spring.datasource.url=jdbc:mariadb://database-2.cv2cumq4slrl.ap-south-2.rds.amazonaws.com:3306/student_db?useSSL=true
spring.datasource.username=admin
spring.datasource.password=Redmi12345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
