server.port=8080
SPRING_DATASOURCE_URL=jdbc:mariadb://database-2.cv2cumq4slrl.ap-south-2.rds.amazonaws.com:3306/student_db?sslMode=trust
SPRING_DATASOURCE_USERNAME=admin
SPRING_DATASOURCE_PASSWORD=Redmi12345
SPRING_JPA_HIBERNATE_DDL_AUTO=update
SPRING_JPA_SHOW_SQL=true
